---
title: "R Notebook"
output: html_notebook
---


```{r}
plot(cars)

library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)


df <- read.csv("C://Users//Hauptfeld//Documents//cs4802a3//entireData.csv", header = TRUE)
dfDot <- read.csv("C://Users//Hauptfeld//Documents//cs4802a3//dotData.csv", header = TRUE)
dfColor <- read.csv("C://Users//Hauptfeld//Documents//cs4802a3//colorData.csv", header = TRUE)


```



Testing entire data
```{r}
df %>%
  ggplot(aes(chartType, log(abs(givenAnswer-expectedAnswer) + 1/8, 2))) +
  #  geom_point() +
    stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5) +
    coord_flip()

```

Testing just dot data
```{r}
dfDot %>%
  ggplot(aes(chartType, log(abs(givenAnswer-expectedAnswer) + 1/8, 2))) +
  #  geom_point() +
    stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5) +
    coord_flip()

```

Testing just color data
```{r}
dfColor %>%
  ggplot(aes(chartType, log(abs(givenAnswer-expectedAnswer) + 1/8, 2))) +
  #  geom_point() +
    stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5) +
    coord_flip()

```

